# Generated by Django 2.2.5 on 2021-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admission',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
