# Generated by Django 2.2.5 on 2021-05-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('BBIT', 'BBIT'), ('ICT', 'ICT'), ('EDUCATION', 'EDUCATION'), ('PSYCHOLOGY', 'PSYCHOLOGY'), ('BHTM', 'BHTM')], default=None, max_length=10, null=True),
        ),
    ]
